// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/prog8/sqlc-testdata/pkg"
)

type Override struct {
	ONE   pkg.CustomType
	Two   int64
	Three pkg.CustomType
	Four  []byte
	Five  []pkg.CustomType
}
